apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-namespace-quota
  namespace: your-namespace  # Replace with your desired namespace
spec:
  hard:
    pods: "10"      # Maximum number of pods that can be created in the namespace
    requests.cpu: "4"    # Total CPU requests allowed in the namespace (in CPU units)
    requests.memory: 8Gi  # Total Memory requests allowed in the namespace (in bytes or with appropriate suffix)
    limits.cpu: "8"      # Total CPU limits allowed in the namespace (in CPU units)
    limits.memory: 16Gi  # Total Memory limits allowed in the namespace (in bytes or with appropriate suffix)
