apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-ssh-secret
  namespace: argocd
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
                 QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFB
                 d0VBQVFBQUFZRUFyU016eFc2UGIzUXRFeDk0LzVMVGVOSktkQWpXdXAwZVhtdHM2RDJYTkxjRGdB
                 QzAyTXN5CnVWNzdjbTZ0OFNXVms3dk9BZ2xsUTZ6a3lPQ0Z2aDc3akNFMEV0eEJpOTMyQ3M4MHhq
                 OThvUWVxUWR1blBTUzk2NTVqNUwKYUpwV0ora2R0R0RFbzdHMlNUUXBBcGRYY0NBKzY0UTNyVzIy
                 cDJoSjFLZFE3OHhVNTE5bjg3RXBUdFZ5VktLSWhRVk1nMQpIa2QvcEEvMnRXNUZIRVVxcFJSVG51
                 KzYrcy9iUjJLdFpIaXBzTjJ0TzIxM1pydldUcTU0WkZWaXhpU1JObkoxSEJ1aG50CnRoYzZmWkZh
                 aVJIY29mcW1NQzI1MXFhQmFmc0QybFgxbUFsQzQrWTJIMEZIaDI0R29yN3VZeEt3bGN5R0RPNFFI
                 QXhZYUgKVGFJVGF5WGllQkZBZjA1NWF2NjVCZ3Y3N0tsNFp5UWR2QW4zeW5DbXVEc3dVUWpoRy9H
                 OCsycTRyb2tEbTlaN2xQeVhEbgpMNi9qZVRoZno1alV2RWdXY1dxQ2RqdHdubnlIMktkT1hWQWdv
                 QWJaWWk4M3FNMnF6K05FOTh1M01WdjFWWHRha3ErT2FvCm9IVXhhT2ZIRCtVRE8wUVdhY2hLdjcz
                 SUFQT3ZVb1hWY25IdnFtenRBQUFGa0FxdE56Z0tyVGM0QUFBQUIzTnphQzF5YzIKRUFBQUdCQUsw
                 ak04VnVqMjkwTFJNZmVQK1MwM2pTU25RSTFycWRIbDVyYk9nOWx6UzNBNEFBdE5qTE1ybGUrM0p1
                 cmZFbApsWk83emdJSlpVT3M1TWpnaGI0ZSs0d2hOQkxjUVl2ZDlnclBOTVkvZktFSHFrSGJwejBr
                 dmV1ZVkrUzJpYVZpZnBIYlJnCnhLT3h0a2swS1FLWFYzQWdQdXVFTjYxdHRxZG9TZFNuVU8vTVZP
                 ZGZaL094S1U3VmNsU2lpSVVGVElOUjVIZjZRUDlyVnUKUlJ4RktxVVVVNTd2dXZyUDIwZGlyV1I0
                 cWJEZHJUdHRkMmE3MWs2dWVHUlZZc1lra1RaeWRSd2JvWjdiWVhPbjJSV29rUgozS0g2cGpBdHVk
                 YW1nV243QTlwVjlaZ0pRdVBtTmg5QlI0ZHVCcUsrN21NU3NKWE1oZ3p1RUJ3TVdHaDAyaUUyc2w0
                 bmdSClFIOU9lV3IrdVFZTCsreXBlR2NrSGJ3Sjk4cHdwcmc3TUZFSTRSdnh2UHRxdUs2SkE1dldl
                 NVQ4bHc1eSt2NDNrNFg4K1kKMUx4SUZuRnFnblk3Y0o1OGg5aW5UbDFRSUtBRzJXSXZONmpOcXMv
                 alJQZkx0ekZiOVZWN1dwS3ZqbXFLQjFNV2pueHcvbApBenRFRm1uSVNyKzl5QUR6cjFLRjFYSng3
                 NnBzN1FBQUFBTUJBQUVBQUFGL1pjak1Kc1ZZamEwKzBuOHVJeEd1UU5sZjY5CmRHWlc3NDY0azcv
                 VXc0R0VWL1NVRWhFRkprLzVWWFBXN1QwM0RFL3BUcUIwaCt2OHBrdGJOSTdQeEo1WmVmaFhiM0Vj
                 THIKWW05dUZ4NDdwbTliS0Z4NWRQaWtybC92V2dYMTVjU0JwRDNFY0hVelNtZFdLMHVWRS9saXRl
                 MGhab3BReGExUS82VjRvRgppdlFVOWZDZ3JDTDZwZDNWMk91MFZuOUcrK3lvNDkrN1ZtMUVKL1hw
                 OUs4c0dBWjIrSC9PczFma0lFcll4Q05qZ2NIMU83Clhpb1BVekkrbEwyZDA5NnJmOWJKQ1ltd1pG
                 UVhudVdqdm1ObDlUZWJ3UHd3clE5YW9DRDU2WTJyNFgzUExoN1NndW94UGgKK1V6M3B1aC95WlN4
                 a3BHUzBJUGRqaGdDaTJ6cnN3YU15K3BjeU12cm4yMWxyVHlVRE9YZFFETnNJdUxGTFRvMzlVeWtW
                 eApRUnVNUU5ZYTZQSVRsQjJ0VSs2T1UvZmZrM3VMS3JLVjhYbGdMRkV6cm95ZlBtWUM0UWx2TUZ4
                 SUVQdGJ3K2JnbG9XV1g0Cm9WUVpmcTZ6ZS9XRzhaTVJiTlNldWRlaHNoaWFCWGhMdDZBdHE2dG5Q
                 Vm1qRmw1d01GdURPZ3MwUzFhcmF0WnVFQUFBREEKUlMyNzJreTVud3pxVTJuM0p0WFdvUmZXU1py
                 ZkhPWXRaanREYlpQTDVoK1JMNTl3N1B2NmJ6VGF2ODRPS01taTZiS1doVQowY1luZlBzVjhRbW9Q
                 R2R4eFYvRllZRmpjRUlTNEJXb2h2R2kxWFRpa3FldFJ3NEFJUnc4T2tFMHRCM20raDdraDhCU0I5
                 ClNGeWhNZmFzMG4xRkxLa1ZNUzBDVjhvQmpvN1haUTVadEdVVzdRUXF5Z1BBNTE3UXMzQlNNS3Nh
                 cFFqcGdqcCtzZnpLb3YKSWh1NXpqeU05MEcxc3hIZ2ZDa3FTTCtBZjd0eHhBdjkvM3FHbmpNTW1W
                 TU9oVUFBQUF3UURuOC9POHFMWGFFU0F0S09XeQo4d0lTTnJWdHo2TFZhQkF0d3QwZjhXNmdZRE4z
                 NnQyUUZFQzJZUzZCZWZRVFhYTkw0UURsSXJMdWNTK3RpRWV5MDNydHBuCldRYXFYUENBeFVDMHlY
                 eXBPR3RWY0lmRmUzRVcxUG9XeG8yN3NkUnM4RTg4SERKZU9lK0xUY3hZNi9jSWFXK0RmcjdBbWcK
                 SlBQZ1haR3VNdWZFakQyTWQxTlpTYXhncUhyZW9pNHlyYWR1c0h1SHArRklVY0tQa1A2ZHNOdERp
                 NDBka1VzUGtkUFVEYwovNzd3Q1ZhZExXalN2MC9vYVdxbmhqOEgwYjRkMEFBQURCQUw4V1NNczBa
                 ZklQRE40K3lrd0dvWGlMcDA3Q3JBcWhvVXpaCkM0eUdYVnJWc1dTdTM5RS84SWt3alNWRTVRUEdX
                 eDVmUTM0ejVVWnVSNFhVRDRWUGwwSU01dXk0R0dRamVKTS9kdjY5N2kKa2RUdVc1MmZsT1EvbmNq
                 eUhzMk5ZS2JSNWFFaGdpNXhtWkZWKzQwUE5tbkI5bE0yT0lVS0g2elRxTTFHeTh4SjQxc0tlSgpQ
                 Z2xOTUxjTkZIV2NEbkpXd0ZqNXFjYktNZUZpNktrUndRL3YrRWdkc0JxeEV5M1ZpSUhlY2hIeVdP
                 ejhxUlBlUFQ5MC9tCkF1QkVvc1BNZHVVUUFBQUJaa1pYWnZjSE5BYVhBdE1UY3lMVEU0TFRFd0xU
                 RXhBUUlEQkFVRwotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
