apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: &&build_deployment-hpa
  namespace: &&build_namespace
spec:
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: &&build_deployment
  minReplicas: &&min_replica
  maxReplicas: &&max_replica
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
